name: Mirroring

on: [push, delete]

jobs:
  to_github_elliot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:eljanvier2/Telecommande-MoCap.git
          ssh_private_key:
            ${{ secrets.elliot_key }}
  to_github_guillaume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:Lebonvieuxgui/Telecommande-Mocap.git
          ssh_private_key:
            ${{ secrets.guillaume_key}}